const data = {
products:[
    {
        _id:'1',
        name:'Nikon Camera',
        category:'Cameras',
        image:'/images/1.jpg',
        price:30000,
        brand:'Nikon',
        rating:4.5,
        numReviews: 10,
        description:'high quality product',
       },
       {
        _id:'2',
        name:'Anker headphones',
        category:'Headphones',
        image:'/images/2.jpg',
        price:4000,
        brand:'Anker',
        rating:3.5,
        numReviews: 7,
        description:'high quality product',
       },
       {
        _id:'3',
        name:'Canon Projector',
        category:'Projectors',
        image:'/images/3.jpg',
        price:60000,
        brand:'Canon',
        rating:5,
        numReviews: 9,
        description:'high quality product',
       },
       {
        _id:'4',
        name:'LG Monitor',
        category:'Monitor',
        image:'/images/4.jpg',
        price:13000,
        brand:'LG',
        rating:3,
        numReviews: 15,
        description:'high quality product',
       },
       {
        _id:'5',
        name:'Polaroid Camera',
        category:'Cameras',
        image:'/images/5.jpg',
        price:25000,
        brand:'Polaroid',
        rating:4.5,
        numReviews: 17,
        description:'high quality product',
       },
       {
        _id:'6',
        name:'HP Laptop',
        category:'Laptops',
        image:'/images/6.jpg',
        price:65000,
        brand:'HP',
        rating:4.5,
        numReviews: 11,
        description:'high quality product',
       },
],
};
export default data; 